import { v4 as uuid } from "uuid";

import {
  house1,
  house2,
  house3,
  house4,
  house5,
  house6,
  house7,
  house8,
  house9,
} from "./Assets/index";
const House = [
  {
    id: uuid(),
    title: "Palm Harbour",
    price: 2095,
    address: "2699 Green Valley, Highland Lake, FL ",
    img: house1,
    beds: "3",
    bathrooms: "2",
    dimension: "5*7 \u33A1",
    propertyType: "House",
    location: "Highland Lake, FL",
    availabilityDate: "10-July-22",
  },
  {
    id: uuid(),
    title: "Beverly Springfield",
    price: 2700,
    address: "2821 Lake Sivella, Palm Harbour, TX ",
    img: house2,
    beds: "4",
    bathrooms: "2",
    dimension: "6*7.5 \u33A1",
    propertyType: "House",
    location: "Palm Harbour, TX",
    availabilityDate: "15-July-22",
  },
  {
    id: uuid(),
    title: "Faulkner Ave",
    price: 3200,
    address: "909 Woodland St, Michigan, IN ",
    img: house3,
    beds: "5",
    bathrooms: "4",
    dimension: "12*9 \u33A1",
    propertyType: "Villa",
    location: "Michigan, IN",
    availabilityDate: "25-July-22",
  },
  {
    id: uuid(),
    title: "Noxus Harbour",
    price: 3509,
    address: "6372 Blue Horizon, Palm Harbour, TX ",
    img: house4,
    beds: "4",
    bathrooms: "2",
    dimension: "7*10 \u33A1",
    propertyType: "House",
    location: "Palm Harbour, TX",
    availabilityDate: "15-July-22",
  },
  {
    id: uuid(),
    title: "Green Villa",
    price: 4900,
    address: "3423 Abbey Street, Highland Lake, FL ",
    img: house5,
    beds: "6",
    bathrooms: "7",
    dimension: "13*11 \u33A1",
    propertyType: "Villa",
    location: "Highland Lake, FL",
    availabilityDate: "2-July-22",
  },
  {
    id: uuid(),
    title: "Fiery Knot",
    price: 1095,
    address: "2304 Michelly Street, Michigan, IN  ",
    img: house6,
    beds: "5",
    bathrooms: "4",
    dimension: "13*5 \u33A1",
    propertyType: "Villa",
    location: "Michigan, IN",
    availabilityDate: "1-July-22",
  },
  {
    id: uuid(),
    title: "Lavender Eve",
    price: 4356,
    address: "3110 , Highland Lake, FL ",
    img: house7,
    beds: "3",
    bathrooms: "2",
    dimension: "5*7 \u33A1",
    propertyType: "House",
    location: "Highland Lake, FL",
    availabilityDate: "5-July-22",
  },
  {
    id: uuid(),
    title: "Willow World",
    price: 5200,
    address: "3203 Purple Corner, Michigan, IN ",
    img: house8,
    beds: "7",
    bathrooms: "6",
    dimension: "14*15 \u33A1",
    propertyType: "Villa",
    location: "Michigan, IN",
    availabilityDate: "15-July-22",
  },
  {
    id: uuid(),
    title: "Happy Daisy",
    price: 500,
    address: "3004 Starling Side, Highland Lake, FL ",
    img: house9,
    beds: "3",
    bathrooms: "2",
    dimension: "5*7 \u33A1",
    propertyType: "House",
    location: "Highland Lake, FL",
    availabilityDate: "10-July-22",
  },
];

export default House;
